version: "3.8"

services:
  mongo.db.catalog:
    image: mongo:8.0-rc
    container_name: mongo.db.catalog.container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db

  mongo.db.catalog.ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo.db.catalog.ui
    ports:
      - "27032:8081"
    environment: 
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo.db.catalog:27017/
      ME_CONFIG_BASICAUTH: "false"

volumes:
  catalogdb_volume:
