@baseAddress = http://localhost:5160
@courseId = 3fa85f64-5717-4562-b3fc-2c963f66afa7

POST {{baseAddress}}/api/v1/baskets/item
Accept: application/json
Content-Type:application/json
{
  "courseId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "courseName": "Rabbit MQ",
  "coursePrice": 399.99
}

###

DELETE {{baseAddress}}/api/v1/baskets/item/{{courseId}}
Accept:application/json

###

GET {{baseAddress}}/api/v1/baskets/user
Accept:application/json
###
PUT {{baseAddress}}/api/v1/baskets/apply-discount
Accept:application/json
Content-Type:application/json
{
  "coupon":"EFSANECUMA",
  "discountRate":0.1
}

###
PUT {{baseAddress}}/api/v1/baskets/remove-discount
Accept: application/json
Content-Type:application/json

###