@baseAddress = http://localhost:5104
@categoryId = 08dd07f3-40fa-60ae-e880-88fd4e2e000
@courseId = 08dd0970-c8ee-9a9b-e880-88fd4e2e0000
@userId = 00000000-0000-0000-0000-000000000000

GET {{baseAddress}}/api/v1.0/categories
Accept: application/json
###
POST {{baseAddress}}/api/v1.0/categories
Accept: application/json
Content-Type:application/json
{
  "name":"Elektronik"
}
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json

###
DELETE {{baseAddress}}/api/v1.0/categories/08dd07f9-6247-1e6a-e880-88fd4e2e0000
Accept: application/json

###

PUT {{baseAddress}}/api/v1.0/categories
Accept: application/json
Content-Type:application/json
{
     "categoryUpdateDto": {
    "id": "08dd0aef-7c53-77f4-e880-88fd4e2e0000",
    "name": "Category Versioned Updated"
  }
}

###
POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type:application/json
{
  "name": "Azure Devops",
  "description": "This course is very detailed",
  "price": 10,
  "categoryId": "08dd07f3-3509-6cf3-e880-88fd4e2e0000"
}
###

GET {{baseAddress}}/api/v1.0/courses/
Accept: application/json

###

GET {{baseAddress}}/api/v1.0/courses/{{courseId}}
Accept: application/json

###
PUT {{baseAddress}}/api/v1.0/courses
Accept: application/json
Content-Type:application/json
{
  "id": "08dd0970-c8ee-9a9b-e880-88fd4e2e0000",
  "name": "Apache Kafka Course Updated Versioned",
  "description": "This course is very detailed",
  "price": 10,
  "createdDate": "2024-11-20T14:36:56.693Z",
  "categoryId": "08dd07f3-3509-6cf3-e880-88fd4e2e0000"
}

###
DELETE {{baseAddress}}/api/v1.0/courses/08dd0a2b-f883-61ce-e880-88fd4e2e0000
Accept: application/json
###


GET {{baseAddress}}/api/v1.0/courses/user/{{userId}}
Accept: application/json

###