@baseAddress = http://localhost:5104
@categoryId = 08dd07f3-40fa-60ae-e880-88fd4e2e000

GET {{baseAddress}}/api/categories
Accept: application/json
###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type:application/json
{
  "name":"Category4"
}
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json

###
DELETE {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json

###

PUT {{baseAddress}}/api/categories
Accept: application/json
Content-Type:application/json
{
     "categoryUpdateDto": {
    "id": "08dd07f9-6247-1e6a-e880-88fd4e2e0000",
    "name": "Category444"
  }
}

###