@baseAddress = http://localhost:5104
@categoryId = 08dd07f3-40fa-60ae-e880-88fd4e2e000
@courseId = 08dd0970-c8ee-9a9b-e880-88fd4e2e0000

GET {{baseAddress}}/api/categories
Accept: application/json
###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type:application/json
{
  "name":"Ca"
}
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json

###
DELETE {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json

###

PUT {{baseAddress}}/api/categories
Accept: application/json
Content-Type:application/json
{
     "categoryUpdateDto": {
    "id": "08dd07f9-6247-1e6a-e880-88fd4e2e0000",
    "name": "Category444"
  }
}

###
POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type:application/json
{
  "name": "Azure Devops",
  "description": "This course is very detailed",
  "price": 10,
  "categoryId": "08dd07f3-3509-6cf3-e880-88fd4e2e0000"
}
###

GET {{baseAddress}}/api/courses/
Accept: application/json

###

GET {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json

###
PUT {{baseAddress}}/api/courses
Accept: application/json
Content-Type:application/json
{
  "id": "08dd0970-c8ee-9a9b-e880-88fd4e2e0000",
  "name": "Apache Kafka Course Updated",
  "description": "This course is very detailed",
  "price": 10,
  "createdDate": "2024-11-20T14:36:56.693Z",
  "categoryId": "08dd07f3-3509-6cf3-e880-88fd4e2e0000"
}

###